### ISSUE TITLE
binary file 

### ISSUE THREAD

**Issue by komawoyo** [shmilee/openwrt-wndr3700v4#1]
Can you upload binary file for this build?

**Comment by shmilee** [comment]
Sorry, for now I can't, because the poor network. Everytime I try to upload the img(13.9M), github tells me:
`Something went really wrong, and we can’t process that file. `
Maybe I will edit release [v20180918](https://github.com/shmilee/openwrt-wndr3700v4/releases/tag/vv20180918) someday.

**Comment by shmilee** [comment]
img uploaded!
